-- Create educational_resources table for storing educational content
CREATE TABLE IF NOT EXISTS educational_resources (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type ENUM('document', 'infographic', 'video', 'presentation', 'guide') NOT NULL,
    category VARCHAR(100) NOT NULL,
    file_path VARCHAR(500),
    file_size INT,
    file_type VARCHAR(50),
    download_count INT DEFAULT 0,
    thumbnail_path VARCHAR(500),
    video_url VARCHAR(500),
    duration INT, -- in minutes for videos
    language VARCHAR(10) DEFAULT 'en',
    difficulty_level ENUM('beginner', 'intermediate', 'advanced') DEFAULT 'beginner',
    tags JSON,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_type (type),
    INDEX idx_category (category),
    INDEX idx_difficulty (difficulty_level),
    INDEX idx_featured (is_featured),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at)
);
